
package programanumerosaleatorios;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Hashtable;
import java.util.Random;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Gabriel Escobar
 */
public class frm_numeros extends javax.swing.JFrame {
    /**
     * Creates new form frm_numeros
     */
    public frm_numeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(" GENERADOR DE NÚMEROS ALEATORIOS Y ORDENAMIENTO ");

        btn_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_1.setForeground(new java.awt.Color(51, 51, 255));
        btn_1.setText("GENERAR NÚMEROS");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_2.setForeground(new java.awt.Color(51, 51, 255));
        btn_2.setText("ORDENAR NÚMEROS");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tablas Hash ");

        jLabel3.setText("Ordenamiento Shell");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btn_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_2)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        String archivo = "numeros.txt";
        int numerosarchivo = 1000000;
        int cantidadtotal = 20000001;
        Random aleatorios = new Random();
        Hashtable<Integer, Integer> tablas = new Hashtable<Integer, Integer>();
        int aleatorio = 0;
        while (aleatorio < numerosarchivo) {
            int num = aleatorios.nextInt(cantidadtotal)-10000000; 
            if (!tablas.containsKey(num)) { 
                tablas.put(num, 1); 
                aleatorio++;
            }
        }
        try {
            FileWriter arc = new FileWriter(archivo);
            BufferedWriter arch = new BufferedWriter(arc);
            for (Integer num : tablas.keySet()) {
                arch.write(num.toString());
                arch.newLine();
            }
            arch.close();
        } catch (IOException ex) {
            System.out.println("Error!!! no se pudo crear el archivo " + archivo + ": " + ex.getMessage());
        }
        System.out.println("Proceso excitoso, se han creado " + numerosarchivo + " de numeros aleatorios en el archivo " + archivo);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed

        String numerose = "numeros.txt";
        String numerosordenados = "numerosordenados.txt";
        List<Integer> numerosor = new ArrayList<>();
        try (BufferedReader nume = new BufferedReader(new FileReader(numerose))) {
            String leer;
            while ((leer = nume.readLine()) != null) {
                int numero = Integer.parseInt(leer);
                numerosor.add(numero);
            }
        } catch (IOException e) {
            System.err.println("Error!!!! no se pudieron leer los numeros: " + e.getMessage());
            System.exit(1);
        }
        int nu = numerosor.size();
        int funcion = nu / 2;
        while (funcion > 0) {
            for (int i = funcion; i < nu; i++) {
                int dato = numerosor.get(i);
                int j;
                for (j = i; j >= funcion && numerosor.get(j - funcion) > dato; j -= funcion) 
                { 
                 numerosor.set(j, numerosor.get(j - funcion));
                }
                numerosor.set(j, dato);
            }
            funcion /= 2;
        }
        try (FileWriter ar = new FileWriter(numerosordenados)) {
            for (int numero : numerosor) {
                ar.write(numero + "\n");
            }
            System.out.println("Proceso excitoso, se han ordenado y guardado los numeros aleatorios en el archivo " + numerosordenados);
        } catch (IOException e) {
            System.err.println("Error!!! algo salió mal: " + e.getMessage());
            System.exit(1);
        }
    }//GEN-LAST:event_btn_2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
